language: go

go:
  - 1.12.x

before_install:
  - go get github.com/mattn/goveralls
  - chmod +x script/coveralls.sh

script:
  - go test -v ./...
  - script/coveralls.sh --coveralls

notifications:
  email:
    - asd5242539@gmail.com
  on_success: never
  on_failure: always